kind: pipeline
type: kubernetes
name: default

steps:
- name: greeting
  image: alpine
  commands:
  - echo helloz
  - echo worldz

- name: docker
  image: plugins/docker
  settings:
    #username: kevinbacon
    #password: pa55word
    dockerfile: Dockerfile
    repo: 10.10.10.3:8080/tests
    registry: 10.10.10.3:8080
